### ISSUE TITLE
1.2.3 broke for me

### ISSUE THREAD

**Issue by mooreatv** [Koihik/vscode-lua-format#10]
It took me a while to figure out why my formatting started to change

reverted to 1.2.2 and it worked again

my setting is a hardcoded path:

"vscode-lua-format.configPath": "C:\\Users\\Me\\luaformat.cfg"

Btw I wish I could get "use the luaformat.cfg anywhere in the current directory of the file or 1 up" but I could never get any relative paths to work expect hardcoding like above

**Comment by mooreatv** [comment]
thanks for the quick fix! 1.2.4 works indeed

any idea about
- use the luaformat.cfg anywhere in the current directory of the file or 1 up ?

also where is the binary of lua-format installed (so I can use it from command line too, on windows)?

**Comment by Koihik** [comment]
> * use the luaformat.cfg anywhere in the current directory of the file or 1 up ?

I don't think it is necessary. The plugin formats the text in the current window which may not belong to a file.

> also where is the binary of lua-format installed (so I can use it from command line too, on windows)?

You can find the binary in (${extenstion-path}/bin/win32). But I also don't know where vscode extension directories are on Windows.
