### ISSUE TITLE
keep_simple_block_one_line not working anymore

### ISSUE THREAD

**Issue by theKBro** [Koihik/vscode-lua-format#17]
working in version 1.2.4, broken afterwards

**Comment by Koihik** [comment]
Please provide more detail.

**Comment by theKBro** [comment]
with 
`
keep_simple_block_one_line: false
`
in version 1.2.4 its formatting the code like this which is desired format:
```
local test = true

if test == true then
  test = false
end

```

in version 1.3.2 - 1.3.6 this is the result:
```
local test = true

if test == true then test = false end
```

**Comment by Koihik** [comment]
It looks like some version changed it to `keep_simple_control_block_one_line`.

https://github.com/Koihik/LuaFormatter/blob/master/docs/Style-Config.md#keep_simple_control_block_one_line

**Comment by theKBro** [comment]
thanks a lot!
```
keep_simple_function_one_line: false
keep_simple_control_block_one_line: false
```
solved the problem
