### ISSUE TITLE
vscodium marketplace

### ISSUE THREAD

**Issue by lrkwz** [Koihik/vscode-lua-format#35]
I would like to use your extension in `codium`: would you mind publishing to [open-vsx.org](https://open-vsx.org/) in addition to the VS Code Marketplace? The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thank you

**Comment by Koihik** [comment]
Published v1.3.7 to open-vsx.org.
I'm not sure it works.

**Comment by lrkwz** [comment]
Perfect

![immagine](https://user-images.githubusercontent.com/1025560/111980825-1e0afa80-8b07-11eb-9e42-cf3b349d6d64.png)
