### ISSUE TITLE
configPath not work if has ${workspaceRoot} 

### ISSUE THREAD

**Issue by letterbaby** [Koihik/vscode-lua-format#9]
example:    "vscode-lua-format.configPath": "${workspaceRoot}\\.vscode\\lua-format"

//----------------------------------------------------------------------------
function fixDriveCasingInWindows(pathToFix) {
    return (process.platform === 'win32' && pathToFix) ? pathToFix.substr(0, 1).toUpperCase() + pathToFix.substr(1) : pathToFix;
}
exports.fixDriveCasingInWindows = fixDriveCasingInWindows;

function getWorkspaceFolderPath(fileUri) {
    if (fileUri) {
        const workspace = vscode.workspace.getWorkspaceFolder(fileUri);
        if (workspace) {
            return fixDriveCasingInWindows(workspace.uri.fsPath);
        }
    }
    // fall back to the first workspace
    const folders = vscode.workspace.workspaceFolders;
    if (folders && folders.length) {
        return fixDriveCasingInWindows(folders[0].uri.fsPath);
    }
}
exports.getWorkspaceFolderPath = getWorkspaceFolderPath;

function resolvePath(inputPath, workspaceFolder) {
    if (!inputPath || !inputPath.trim())
        return inputPath;
    if (!workspaceFolder && vscode.workspace.workspaceFolders) {
        workspaceFolder = getWorkspaceFolderPath(vscode.window.activeTextEditor && vscode.window.activeTextEditor.document.uri);
    }
    if (workspaceFolder) {
        inputPath = inputPath.replace(/\${workspaceFolder}|\${workspaceRoot}/g, workspaceFolder);
    }
    return inputPath;
}
exports.resolvePath = resolvePath;
//-----------------------------------------------------------------------------------------
    let configPath = vscode.workspace.getConfiguration().get("vscode-lua-format.configPath");
            const binaryPath = vscode.workspace.getConfiguration().get("vscode-lua-format.binaryPath");
						
            const args = ["-si"];
            if (configPath) {
                args.push("-c");
                args.push(resolvePath(configPath));
            }
//------------------------------------------------------------------------------------------

**Comment by evolbug** [comment]
I made a fix for this this yesterday, but a new release will have to be made by author, configPath is going to be relative to project root and will use standard glob patterns provided by vscode, as that's the simplest solution.
After the release will be made you'll be able to just use `.vscode\lua-format`

**Comment by Koihik** [comment]
v1.2.3 is released now with fix of @evolbug .
